import { Character, FactionInfo, WorldviewTerm } from './types';

export const FACTIONS: FactionInfo[] = [
  { id: 'SEOUL_HIGH', name: '서울 주술 고등학교', description: '대한민국의 주술사 양성을 위한 최상위 등급의 특수 고등학교.', color: 'text-blue-400' },
  { id: 'ASSOCIATION', name: '주술 협회', description: '대한민국 주술계의 중심이자 질서를 유지하는 기관.', color: 'text-emerald-400' },
  { id: 'FAMILIES', name: '주술 명가', description: '오랜 역사와 전통, 그리고 강력한 술식을 계승하는 가문들.', color: 'text-amber-400' },
  { id: 'CURSE_USERS', name: '저주사', description: '개인의 욕망을 위해 주술을 사용하는 타락한 이들.', color: 'text-purple-500' },
  { id: 'SPIRITS', name: '주령', description: '인간의 부정적인 감정이 뭉쳐 태어난 재앙.', color: 'text-red-600' },
];

export const WORLDVIEW: WorldviewTerm[] = [
  { title: '시대적 배경', content: '2040년 대한민국. 과학 기술의 발전 이면에 더욱 짙어진 그림자 속에서 주술사와 주령의 전쟁은 계속되고 있다. 민간인들은 여전히 이들의 존재를 모르며, 알게 된 자들은 기억이 지워지거나 사라진다.' },
  { title: '속박 (Binding Vow)', content: '술사 본인에게 의도적으로 불리한 조건을 추가하고 그에 상응하는 주술적 이익이나 강화를 얻어내는 행위. 등가교환의 법칙을 철저히 따른다.' },
  { title: '영역 전개', content: '주술의 정점. 자신의 생득 영역을 주력으로 구현하여 주변 공간을 덮어쓰는 기술. 영역 내에서는 술자의 필중 효과가 부여된다.' },
  { title: '백야 가문', content: '과거 3대 가문 중 하나였으나 주저사들과의 수많은 전투로 인해 거의 몰락한 비운의 명가.' },
  { title: '혈도 가문', content: '개인주의가 극심하며 오직 강자만이 살아남는 잔혹한 규율을 가진 가문.' },
  { title: '광염 가문', content: '자존심이 강하고 가문원 간의 동료애가 넘치는, 불꽃을 다루는 명가.' },
];

export const CHARACTERS: Character[] = [
  // 서울 주술 고등학교
  {
    id: 'han-sin-woo',
    name: '한신우',
    code: 'c',
    gender: '남',
    age: 29,
    mbti: 'ENFJ',
    keywords: ['압도적 여유', '외유내강'],
    description: '학생들을 아끼지만 속을 알 수 없는 얼굴을 하고 있다.',
    role: '서주고 교장',
    technique: '청룡강림',
    domainExpansion: '만경창파운해저',
    domainStatus: 'O',
    grade: '특급',
    quote: "너무 서두르지 마세요. 흐르는 물을 거스르면 결국 다치는 법이니까요.",
    appearance: '흑발, 청안',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'shin-ah-hyun',
    name: '신아현',
    code: 'd',
    gender: '여',
    age: 26,
    mbti: 'INTJ',
    keywords: ['냉철한 카리스마', '완벽주의', '츤데레'],
    description: '역사상 최강의 검사. 학생들의 생존을 최우선으로 중시한다.',
    role: '서주고 교사',
    technique: '낙화천류',
    domainExpansion: '명부혈화원',
    domainStatus: 'O',
    grade: '특급',
    quote: "방금 그 움직임은 60점. 죽고 싶지 않으면 주력을 흘리지 말고 검 끝에 집중해.",
    appearance: '적안, 포니테일 붉은색 머리카락',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'park-soo-hyun',
    name: '박수현',
    code: 'g',
    gender: '여',
    age: 25,
    mbti: 'ISTJ',
    keywords: ['초이성주의', '무심한 다정함', '팩트폭력기'],
    description: '감정보다는 해결책을 제시한다. 데이터 기반의 분석가.',
    role: '서주고 보조교사',
    technique: '신해신경',
    domainExpansion: '가상심층 전뇌옥좌',
    domainStatus: 'O',
    grade: '탈 1급',
    quote: "아무리 날뛰어봤자 데이터상의 변수일 뿐이야.",
    appearance: '녹색 단발, 녹색 눈, 안경',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'han-yujin',
    name: '한유진',
    code: 'h',
    gender: '여',
    age: 19,
    mbti: 'ENTP',
    keywords: ['즉흥적', '마이페이스', '천재적 박자감'],
    description: '지루한 걸 싫어하며 상층부와 의견 충돌로 현재 정학 상태이다.',
    role: '서주고 3학년 (정학)',
    technique: '섬광박동',
    domainExpansion: '광란공연 자색전율',
    domainStatus: 'O',
    grade: '준 1급',
    quote: "심심해서 죽는 줄 알았다고. 자, 이제 누가 나랑 놀아줄 거지?",
    appearance: '보리색 단발, 보라색 눈',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'lee-sujin',
    name: '이수진',
    code: 'j',
    gender: '여',
    age: 18,
    mbti: 'ISFP',
    keywords: ['성실함', '직설적'],
    description: '말수는 적지만 행동이 먼저 앞선다. 묵묵히 할 일을 수행한다.',
    role: '서주고 2학년',
    technique: '취련박속',
    domainExpansion: '수해심연 만록옥죄',
    domainStatus: 'X',
    grade: '3급',
    quote: "아직은 3급이지만... 제가 할 수 있는 일이 있을 거예요.",
    appearance: '연두색 단발, 금안',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'kang-sumin',
    name: '강수민',
    code: 'k',
    gender: '여',
    age: 18,
    mbti: 'ISTJ',
    keywords: ['무미건조', '포커페이스', '논리주의자'],
    description: '표현은 없지만 동료를 깊이 아낀다.',
    role: '서주고 2학년',
    technique: '영도결계',
    domainExpansion: '명동빙옥',
    domainStatus: 'X',
    grade: '2급',
    quote: "시끄럽네요. 그 입부터 얼려버리면 좀 조용해질까요?",
    appearance: '하늘색 장발, 청안',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'oh-hayun',
    name: '오하윤',
    code: 'l',
    gender: '여',
    age: 17,
    mbti: 'ESFP',
    keywords: ['열정폭발', '정의감', '분위기 메이커'],
    description: '친화력이 좋고 신체능력이 뛰어나다. 도끼 주구를 사용한다.',
    role: '서주고 1학년',
    technique: '단순 주술 타격',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '3급',
    quote: "무서워 죽겠지만... 도망치면 혼난단 말이야! 에잇, 죽어라!",
    appearance: '주황색 양갈래, 금안',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'yoon-sarang',
    name: '윤사랑',
    code: 'm',
    gender: '여',
    age: 17,
    mbti: 'ENFP',
    keywords: ['애정결핍(컨셉)', '감정풍부', '러블리 싸이코'],
    description: '타인의 감정에 예민하며 집착적인 면모가 있다.',
    role: '서주고 1학년',
    technique: '연심박쇄',
    domainExpansion: '애욕낙원 심장유희',
    domainStatus: 'X',
    grade: '2급',
    quote: "미움보다는 사랑의 힘이 더 강하다는 걸 증명해 보일게요.",
    appearance: '핑크색 장발, 청안',
    faction: 'SEOUL_HIGH'
  },
  {
    id: 'myung-yejin',
    name: '명예진',
    code: 'n',
    gender: '여',
    age: 19,
    mbti: 'ISTP',
    keywords: ['염세주의', '책임감', '자발적 아웃사이더'],
    description: '주술의 위험성을 이유로 스스로를 억제한다.',
    role: '서주고 3학년',
    technique: '명부중력',
    domainExpansion: '흑월침식 무저심연',
    domainStatus: '불완전',
    grade: '준 2급 (억제중)',
    quote: "제 주력엔 온기가 없어요. 오직 공허한 정적뿐이죠. 자, 조용히 잠들 시간이에요.",
    appearance: '검정과 흰색의 조화 단발, 금안',
    faction: 'SEOUL_HIGH'
  },
  
  // 협회
  {
    id: 'choi-ayoung',
    name: '최아영',
    code: 'p',
    gender: '여',
    age: 31,
    mbti: 'ENTJ',
    keywords: ['절대권위', '냉혹한 결단력', '완성형'],
    description: '사소한 감정에 휘둘리지 않으며 대의를 위해 움직인다.',
    role: '대한 주술사 총괄 협회장',
    technique: '천벌뇌격',
    domainExpansion: '뇌전신궁 만뢰심판',
    domainStatus: 'O',
    grade: '특급',
    quote: "협회장이라는 자리... 생각보다 비린내가 많이 나는군요. 손에 묻은 피는 씻어내면 그만이지만.",
    appearance: '짙은 청색 단발, 청안',
    faction: 'ASSOCIATION'
  },
  {
    id: 'kwon-yechan',
    name: '권예찬',
    code: 'q',
    gender: '남',
    age: 32,
    mbti: 'ENTP',
    keywords: ['호쾌함', '의리파', '자유로움'],
    description: '격식에 얽매이는 것을 싫어하고 본능적인 감각을 추구한다.',
    role: '인천 주술 본부장',
    technique: '적영의 소용돌이',
    domainExpansion: '명해혈전 흑야만개',
    domainStatus: 'O',
    grade: '1급',
    quote: "항구의 밤바람은 맵군. 이 비릿한 피 냄새만 아니었다면 술 한잔하기 딱 좋은 날씨인데 말이야.",
    appearance: '붉은 머리, 청안',
    faction: 'ASSOCIATION'
  },
  {
    id: 'shin-geonwoo',
    name: '신건우',
    code: 'r',
    gender: '남',
    age: 22,
    mbti: 'ENTP',
    keywords: ['기회주의', '돈미새', '능글맞음'],
    description: '항상 자신만만한 미소로 상대를 자신의 페이스로 끌어들인다.',
    role: '인천 본부 1과 부장',
    technique: '황금침식',
    domainExpansion: '명부금고 만인멸죄',
    domainStatus: '불완전',
    grade: '준 1급',
    quote: "어라, 전세가 역전됐네? 미안하지만 난 지는 싸움엔 판돈 안 걸거든.",
    appearance: '은발과 금발이 섞임, 금안',
    faction: 'ASSOCIATION'
  },
  {
    id: 'jung-haewon',
    name: '정해원',
    code: 't',
    gender: '여',
    age: 29,
    mbti: 'ISTP',
    keywords: ['무자비함', '현실주의', '거친 분위기'],
    description: '말보다는 행동, 절차보다 확실한 결과를 중시한다.',
    role: '부산 주술 본부장',
    technique: '심해청염',
    domainExpansion: '명계해루 침묵옥좌',
    domainStatus: 'O',
    grade: '탈 1급',
    quote: "상황 보고는 필요 없다. 내 눈으로 확인했고, 내 손으로 끝낼 거니까. 5분이면 충분해.",
    appearance: '푸른색 머리, 청안',
    faction: 'ASSOCIATION'
  },
  {
    id: 'na-seungmin',
    name: '나승민',
    code: 'v',
    gender: '남',
    age: 23,
    mbti: 'ESTJ',
    keywords: ['희생정신', '워커홀릭', '규율 중시'],
    description: '절제된 생활을 하며 명령 체계를 절대적으로 따른다.',
    role: '부산 본부 1과 부장',
    technique: '적영섬격',
    domainExpansion: '철혈전장 단죄지경',
    domainStatus: 'O',
    grade: '1급',
    quote: "부산 1과, 현장 도착. 지금부터 이 구역의 지휘권은 내가 갖는다. 이의 있나?",
    appearance: '민트색 머리, 적안',
    faction: 'ASSOCIATION'
  },

  // 가문
  {
    id: 'yoo-jihoon',
    name: '유지훈',
    code: 'w',
    gender: '남',
    age: 24,
    mbti: 'ESTP',
    keywords: ['자신감', '호승심', '피지컬'],
    description: '복잡한 이론보다 감각과 압도적인 피지컬로 승부한다.',
    role: '광염 가문 장남',
    technique: '홍련아권',
    domainExpansion: '광염지옥 만겁업화',
    domainStatus: 'O',
    grade: '준 1급',
    quote: "난 최고가 될 거야. 누구도 범접할 수 없는 주술사로.",
    appearance: '금발, 적안',
    faction: 'FAMILIES'
  },
  {
    id: 'shin-dayeon',
    name: '신다연',
    code: 'y',
    gender: '여',
    age: 25,
    mbti: 'INTP',
    keywords: ['퇴폐미', '냉소적', '강박적'],
    description: '가문을 혐오하지만 그 힘을 가장 완벽하게 다루는 모순적인 존재.',
    role: '혈도 가문 장녀',
    technique: '적살식',
    domainExpansion: '혈지연옥 사생낙인',
    domainStatus: 'O',
    grade: '1급',
    quote: "죽음이 구원이라고 믿지는 않아. 하지만 적어도 이 지독한 현실에서는 벗어나게 해주겠지.",
    appearance: '은발, 적안',
    faction: 'FAMILIES'
  },

  // 저주사
  {
    id: 'seo-nahee',
    name: '서나희',
    code: 'B',
    gender: '여',
    age: 18,
    mbti: 'ENFP',
    keywords: ['소악마', '가학적', '잔인함'],
    description: '자신이 흥미를 느끼는 대상에게 과도하게 집착한다.',
    role: '저주사',
    technique: '자색연쇄',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '2급',
    quote: "아하하! 조금만 더 비명을 질러봐. 그 소리, 지금 정말 아름답거든.",
    appearance: '보라색 양갈래, 보라색 눈',
    faction: 'CURSE_USERS'
  },
  {
    id: 'jo-yoonha',
    name: '조윤하',
    code: 'C',
    gender: '여',
    age: 30,
    mbti: 'INFJ',
    keywords: ['매혹적', '관조적', '신비주의'],
    description: "파괴되는 과정의 '미학'에 집착하며 방해하는 자들을 제거한다.",
    role: '저주사',
    technique: '홍월인력',
    domainExpansion: '월하낙원 홍월지심판',
    domainStatus: 'O',
    grade: '1급',
    quote: "달빛이 참 곱네요. 당신의 마지막을 장식하기에 부족함이 없죠?",
    appearance: '갈색 장발, 적안',
    faction: 'CURSE_USERS'
  },
  {
    id: 'han-seoyoon',
    name: '한서윤',
    code: 'D',
    gender: '여',
    age: 27,
    mbti: 'INTJ',
    keywords: ['허무주의', '복수귀', '냉혈'],
    description: '철저하게 계산된 움직임, 필요한 경우에만 서늘한 독설을 내뱉는다.',
    role: '저주사',
    technique: '흑연장례',
    domainExpansion: '흑야지옥 만종지침묵',
    domainStatus: 'O',
    grade: '1급',
    quote: "기도할 시간은 주지 않아. 죽음엔 소리가 필요 없으니까.",
    appearance: '흑색 장발, 청안',
    faction: 'CURSE_USERS'
  },

  // 주령
  {
    id: 'jeol-hae-seong',
    name: '절해성',
    code: 'G',
    keywords: ['비극', '재앙', '최강'],
    description: "500년 전 '최강'의 주술사였으나 배신과 비극으로 인해 재앙이 되었다.",
    technique: '만상귀해',
    domainExpansion: '무간심해 종언지영면',
    domainStatus: 'O',
    grade: '특급',
    faction: 'SPIRITS'
  },
  {
    id: 'bul-sa-hae',
    name: '불사해',
    code: 'H',
    keywords: ['원한', '전쟁', '괴수'],
    description: '100년 전 전쟁의 참화 속에서 스러져간 생명의 원한이 뭉친 거대 괴수.',
    technique: '만인병고',
    domainExpansion: '시해고원 영원지전야',
    domainStatus: 'O',
    grade: '특급',
    faction: 'SPIRITS'
  },
  {
    id: 'hae-rak',
    name: '해락',
    code: 'J',
    keywords: ['시체', '실'],
    description: '수많은 손으로 상대를 잡아 끌어 주력을 빨아들인다.',
    technique: '시체를 얽어매는 실',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '2급',
    faction: 'SPIRITS'
  },
  {
    id: 'jan-rang',
    name: '잔랑',
    code: 'K',
    keywords: ['늑대인간', '식욕'],
    description: '늑대인간 형태로 무엇도 남기지 않고 먹어치우려 한다.',
    technique: '포식',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '3급',
    faction: 'SPIRITS'
  },
  {
    id: 'gwang-hyeol-ma',
    name: '광혈마',
    code: 'L',
    keywords: ['피', '폭주'],
    description: '미쳐버린 피의 마물. 자신의 피를 연소시켜 폭발적인 힘을 낸다.',
    technique: '혈액 연소',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '1급',
    faction: 'SPIRITS'
  },
  {
    id: 'muk-cheol-ryeong',
    name: '묵철령',
    code: 'M',
    keywords: ['메뚜기', '살기', '갑각'],
    description: '베이지 않는 단단함과 주물로 벼려진 듯한 차가운 살기를 가졌다.',
    technique: '강철 갑각',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '2급',
    faction: 'SPIRITS'
  },
  {
    id: 'mang-hyang-ju',
    name: '망향주',
    code: 'P',
    keywords: ['소녀', '정신공격'],
    description: '얼굴이 일그러진 소녀의 형상. 정신의 약한 부분을 공략한다.',
    technique: '정신 오염',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '3급',
    faction: 'SPIRITS'
  },
  {
    id: 'heo-gak-chung',
    name: '허각충',
    code: 'Q',
    keywords: ['고치', '금속', '압살'],
    description: '은빛 뼈대의 고치. 거대한 덩치로 상대를 덮쳐 으스러뜨린다.',
    technique: '금속 뼈대',
    domainExpansion: '없음',
    domainStatus: 'X',
    grade: '1급',
    faction: 'SPIRITS'
  }
];